### PR TITLE
feat: add support for Vue 3

### LINKED ISSUE #10: Build vuejs package

### PR DESCRIPTION
**Pull request by selemondev**

### CODE REVIEW

**Review by vedantnn71 — CHANGES_REQUESTED** [review]
Can you please use types from the @withbeacon/core package instead of copying them over here? :)

**Comment by vedantnn71** [comment]
Also, can you please format the code?

**Review by vedantnn71 — CHANGES_REQUESTED** [review]
I think this file is obsolete as this test does not make any sense to me so can you please remove vitest and this test dir?

**Comment by selemondev** [comment]
> I think this file is obsolete as this test does not make any sense to me so can you please remove vitest and this test dir?

OK.

**Pull request closed without merging**
